x-citus-coor: &citus-coor
  image: citusdata/citus:latest
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ppgpass}
  restart: unless-stopped

x-citus-worker: &citus-worker
  image: citusdata/citus:latest
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ppgpass}
  restart: unless-stopped

services:
  # =====================
  # SERVICE HC
  # =====================
  coor-hc:
    <<: *citus-coor
    container_name: coor-hc
    ports:
      - "5431:5432"
    volumes:
      - coor_hc_data:/var/lib/postgresql/data
      - ./init-sql/init-hc.sql:/docker-entrypoint-initdb.d/init-hc.sql
    depends_on:
      - worker1-hc
      - worker2-hc

  worker1-hc:
    <<: *citus-worker
    container_name: worker1-hc
    volumes:
      - worker1_hc_data:/var/lib/postgresql/data

  worker2-hc:
    <<: *citus-worker
    container_name: worker2-hc
    volumes:
      - worker2_hc_data:/var/lib/postgresql/data

  # =====================
  # SERVICE DOCUMENT
  # =====================
  coor-doc:
    <<: *citus-coor
    container_name: coor-doc
    ports:
      - "5432:5432"
    volumes:
      - coor_doc_data:/var/lib/postgresql/data
      - ./init-sql/init-doc.sql:/docker-entrypoint-initdb.d/init-doc.sql
    depends_on:
      - worker1-doc
      - worker2-doc

  worker1-doc:
    <<: *citus-worker
    container_name: worker1-doc
    volumes:
      - worker1_doc_data:/var/lib/postgresql/data

  worker2-doc:
    <<: *citus-worker
    container_name: worker2-doc
    volumes:
      - worker2_doc_data:/var/lib/postgresql/data

volumes:
  coor_hc_data:
  worker1_hc_data:
  worker2_hc_data:
  coor_doc_data:
  worker1_doc_data:
  worker2_doc_data: