version: '3.8'

x-citus-coordinator: &citus-coordinator
  image: citusdata/citus:12.2
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgrespw
  restart: unless-stopped

x-citus-worker: &citus-worker
  image: citusdata/citus:12.2
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgrespw
  restart: unless-stopped

services:
  # =====================
  # PGPOOL ENTRY POINT
  # =====================
  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    restart: unless-stopped
    ports:
      - "9999:5432"
    environment:
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./pgpool/pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
      - ./pgpool/pool_hba.conf:/opt/bitnami/pgpool/conf/pool_hba.conf
    depends_on:
      - coordinator_hc
      - coordinator_doc
      - coordinator_finance
      - coordinator_risk
      - coordinator_market

  # =====================
  # SERVICE 1
  # =====================
  coordinator_hc:
    <<: *citus-coordinator
    container_name: coordinator_hc
    ports:
      - "5431:5432"
    volumes:
      - citus/cor_hc:/var/lib/postgresql/data
      - ./service1/init-scripts:/docker-entrypoint-initdb.d
    depends_on:
      - worker1a_hc
      - worker1b_hc

  worker1a_hc:
    <<: *citus-worker
    container_name: worker1a_hc
    volumes:
      - worker1a_hc_data:/var/lib/postgresql/data

  worker1b_hc:
    <<: *citus-worker
    container_name: worker1b_hc
    volumes:
      - worker1b_hc_data:/var/lib/postgresql/data

  # =====================
  # SERVICE 2
  # =====================
  coordinator_svc2:
    <<: *citus-coordinator
    container_name: coordinator_svc2
    ports:
      - "5432:5432"
    volumes:
      - coordinator_svc2_data:/var/lib/postgresql/data
      - ./service2/init-scripts:/docker-entrypoint-initdb.d
    depends_on:
      - worker1a_svc2
      - worker1b_svc2

  worker1a_svc2:
    <<: *citus-worker
    container_name: worker1a_svc2
    volumes:
      - worker1a_svc2_data:/var/lib/postgresql/data

  worker1b_svc2:
    <<: *citus-worker
    container_name: worker1b_svc2
    volumes:
      - worker1b_svc2_data:/var/lib/postgresql/data

  # =====================
  # SERVICE 3,4,5
  # (pola sama dengan service1 & 2)
  # =====================