version: '3.8'

x-citus-coor: &citus-coor
  image: citusdata/citus:12.2
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ppgpass}
  restart: unless-stopped

x-citus-worker: &citus-worker
  image: citusdata/citus:12.2
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ppgpass}
  restart: unless-stopped

services:
  # =====================
  # PGPOOL ENTRY POINT
  # =====================
  pgpool:
    image: bitnami/pgpool:4
    container_name: pgpool
    restart: unless-stopped
    ports:
      - "9999:5432"
    environment:
      - PGPOOL_POSTGRES_USERNAME=${POSTGRES_USER:-postgres}
      - PGPOOL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ppgpass}
    volumes:
      - ./pgpool/pgpool.conf:/opt/bitnami/pgpool/conf/pgpool.conf
      - ./pgpool/pool_hba.conf:/opt/bitnami/pgpool/conf/pool_hba.conf
    depends_on:
      - coor_hc
      - coor_doc
      - coor_finance
      - coor_risk
      - coor_market

  # =====================
  # SERVICE 1
  # =====================
  coor_hc:
    <<: *citus-coor
    container_name: coor_hc
    ports:
      - "5431:5432"
    volumes:
      - citus/cor_hc:/var/lib/postgresql/data
      - ./service1/init-scripts:/docker-entrypoint-initdb.d
    depends_on:
      - worker1_hc
      - worker2_hc

  worker1_hc:
    <<: *citus-worker
    container_name: worker1_hc
    volumes:
      - worker1_hc_data:/var/lib/postgresql/data

  worker2_hc:
    <<: *citus-worker
    container_name: worker2_hc
    volumes:
      - worker2_hc_data:/var/lib/postgresql/data

  # =====================
  # SERVICE 2
  # =====================
  coor_doc:
    <<: *citus-coor
    container_name: coor_doc
    ports:
      - "5432:5432"
    volumes:
      - coor_doc_data:/var/lib/postgresql/data
      - ./service2/init-scripts:/docker-entrypoint-initdb.d
    depends_on:
      - worker1_doc
      - worker2_doc

  worker1_doc:
    <<: *citus-worker
    container_name: worker1_doc
    volumes:
      - worker1_doc_data:/var/lib/postgresql/data

  worker2_doc:
    <<: *citus-worker
    container_name: worker2_doc
    volumes:
      - worker2_doc_data:/var/lib/postgresql/data