x-citus-coor: &citus-coor
  image: citusdata/citus:latest
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpass}
  volumes:
    - ./init-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  restart: unless-stopped

x-citus-worker: &citus-worker
  image: citusdata/citus:latest
  environment:
    - POSTGRES_USER=${POSTGRES_USER:-postgres}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpass}
  restart: unless-stopped

services:
  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    depends_on:
      - coor-hc
      - coor-doc
      - coor-fin
      - coor-risk
      - coor-market
    restart: always

  coor-hc:
    <<: *citus-coor
    container_name: coor-hc
    ports:
      - "5431:5432"
    volumes:
      - coor_hc_data:/var/lib/postgresql/data
      - /citus/hc/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /citus/hc/logs/coordinator:/var/log/postgresql
      - /citus/hc/backups/coordinator:/var/backups/postgresql
      - /citus/hc/scripts:/opt/scripts:ro

  coor-doc:
    <<: *citus-coor
    container_name: coor-doc
    ports:
      - "5432:5432"
    volumes:
      - coor_doc_data:/var/lib/postgresql/data
      - /citus/document/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /citus/document/logs/coordinator:/var/log/postgresql
      - /citus/document/backups/coordinator:/var/backups/postgresql
      - /citus/document/scripts:/opt/scripts:ro

  coor-fin:
    <<: *citus-coor
    container_name: coor-fin
    ports:
      - "5433:5432"
    volumes:
      - coor_fin_data:/var/lib/postgresql/data
      - /citus/finance/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /citus/finance/logs/coordinator:/var/log/postgresql
      - /citus/finance/backups/coordinator:/var/backups/postgresql
      - /citus/finance/scripts:/opt/scripts:ro

  coor-risk:
    <<: *citus-coor
    container_name: coor-risk
    ports:
      - "5434:5432"
    volumes:
      - coor_risk_data:/var/lib/postgresql/data
      - /citus/risk/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /citus/risk/logs/coordinator:/var/log/postgresql
      - /citus/risk/backups/coordinator:/var/backups/postgresql
      - /citus/risk/scripts:/opt/scripts:ro

  coor-market:
    <<: *citus-coor
    container_name: coor-market
    ports:
      - "5435:5432"
    volumes:
      - coor_market_data:/var/lib/postgresql/data
      - /citus/market/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - /citus/market/logs/coordinator:/var/log/postgresql
      - /citus/market/backups/coordinator:/var/backups/postgresql
      - /citus/market/scripts:/opt/scripts:ro

  worker-node1:
    <<: *citus-worker
    container_name: worker-node1
    volumes:
      - worker_node1_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker1:/var/log/postgresql
      - /citus/worker/backups/worker1:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node2:
    <<: *citus-worker
    container_name: worker-node2
    volumes:
      - worker_node2_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker2:/var/log/postgresql
      - /citus/worker/backups/worker2:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node3:
    <<: *citus-worker
    container_name: worker-node3
    volumes:
      - worker_node3_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker3:/var/log/postgresql
      - /citus/worker/backups/worker3:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node4:
    <<: *citus-worker
    container_name: worker-node4
    volumes:
      - worker_node4_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker4:/var/log/postgresql
      - /citus/worker/backups/worker4:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node5:
    <<: *citus-worker
    container_name: worker-node5
    volumes:
      - worker_node5_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker5:/var/log/postgresql
      - /citus/worker/backups/worker5:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node6:
    <<: *citus-worker
    container_name: worker-node6
    volumes:
      - worker_node6_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker6:/var/log/postgresql
      - /citus/worker/backups/worker6:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node7:
    <<: *citus-worker
    container_name: worker-node7
    volumes:
      - worker_node7_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker7:/var/log/postgresql
      - /citus/worker/backups/worker7:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node8:
    <<: *citus-worker
    container_name: worker-node8
    volumes:
      - worker_node8_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker8:/var/log/postgresql
      - /citus/worker/backups/worker8:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node9:
    <<: *citus-worker
    container_name: worker-node9
    volumes:
      - worker_node9_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker9:/var/log/postgresql
      - /citus/worker/backups/worker9:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

  worker-node10:
    <<: *citus-worker
    container_name: worker-node10
    volumes:
      - worker_node10_data:/var/lib/postgresql/data
      - /citus/worker/logs/worker10:/var/log/postgresql
      - /citus/worker/backups/worker10:/var/backups/postgresql
      - /citus/worker/scripts:/opt/scripts:ro

volumes:
  coor_hc_data:
  coor_doc_data:
  coor_fin_data:
  coor_risk_data:
  coor_market_data:
  worker_node1_data:
  worker_node2_data:
  worker_node3_data:
  worker_node4_data:
  worker_node5_data:
  worker_node6_data:
  worker_node7_data:
  worker_node8_data:
  worker_node9_data:
  worker_node10_data:
