x-postgres-common: &postgres-common
  image: postgres:latest
  restart: always
  expose:
    - "5432"
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  networks:
    - dbpool_net

services:
  dev_db:
    <<: *postgres-common
    container_name: dev_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - /postgres/dev_data:/var/lib/postgresql/data

#   hc_db:
#     <<: *postgres-common
#     container_name: hc_postgres_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - /postgres/hc_data:/var/lib/postgresql/data

#   risk_db:
#     <<: *postgres-common
#     container_name: risk_postgres_db
#     ports:
#       - "5433:5432"
#     volumes:
#       - /postgres/risk_data:/var/lib/postgresql/data

#   document_db:
#     <<: *postgres-common
#     container_name: document_postgres_db
#     ports:
#       - "5434:5432"
#     volumes:
#       - /postgres/document_data:/var/lib/postgresql/data

#   finance_db:
#     <<: *postgres-common
#     container_name: finance_postgres_db
#     ports:
#       - "5435:5432"
#     volumes:
#       - /postgres/finance_data:/var/lib/postgresql/data

#   market_competition_db:
#     <<: *postgres-common
#     container_name: market_competition_postgres_db
#     ports:
#       - "5436:5432"
#     volumes:
#       - /postgres/market_competition_data:/var/lib/postgresql/data 

# volumes:
#   hc_data:
#   risk_data:
#   document_data:
#   finance_data:
#   market_competition_data:

networks:
  dbpool_net: