version: "3.8"

services:
  nginx:
    container_name: nginx-reverse-proxy_net
    image: nginx:latest
    ports:
      - "5432:80"
    volumes:
      - ./log/:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./my.conf:/etc/nginx/conf.d/my.conf
    networks:
      - proxy_net
    restart: always
    depends_on:
      - hc_db
      - risk_db
      - document_db
      - finance_db
      - market_competition_db

networks:
  proxy_net:
    external: true
