services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log/:/var/log/nginx/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/my.conf:/etc/nginx/conf.d/my.conf
      - ./certs:/etc/nginx/certs:ro
    networks:
      - nginx_net

networks:
  nginx_net:
    name: nginx_net
    driver: bridge